experiment_directory: /Users/kpandit/pyseq-image/src/demo/
output_directory: /nethome/kpandit/hudson/results/
stains:
  # cycle:
  #   channel1: marker1
  #   channel2: marker2
  1:
    610: GFAP
  2:
    740: ELAVL2
  3:
    558: LMN1b
  4:
    687: MBP
  5:
    558: LMN1b_5
    610: GFAP_5
    687: MBP_5
    740: ELAVL2_5
segmentation:
  marker: LMN1b_5
unmix:
  max_iter: 10               # Max iterations to optimize unmixing
gpu_spec:
  partition: gpu
  gres: gpu:tesla:1
resources:
    # or specify in .config/dask/jobqueue.yaml
    # log_directory: None
  dask_worker:
