experiment_directory: /nethome/kpandit/pyseq-image/src/demo/
output_directory: /nethome/kpandit/hudson/results/
resources:
  partition: pi3
  time: '1:00:00'
  mem: 16G
  dask_worker:
    # or specify in .config/dask/jobqueue.yaml
    log_directory: None
